### ISSUE TITLE
how to make the 4-bit anotation image?

### ISSUE THREAD

**Issue by mkmk001** [z-x-yang/CFBI#20]
I want to make my own dataset but I do not known how to get the 4-bit depth anotation.The PS software could only make the 8-bit ones.And when I use them,my GPU memory is not enouph.

**Comment by z-x-yang** [comment]
How many objects in your annotation?

The maximum value in the mask annotation should be the same as the number of containing objects. Since we use the maximum mask value to decide how many objects are in the corresponding video sequence.

If the maximum value is 5, for example, and there is only 1 object in the video. The inference code will predict this object with 4 empty objects (because they don't have any mask region), and you will need much more unnecessary GPU memory.

Set the mask value to be 1 for the first object, to be 2 for the second, and so on.

**Comment by z-x-yang** [comment]
It seems that the problem has been solved. I'll close the issue.
