### ISSUE TITLE
About YouTube-VOS testing

### ISSUE THREAD

**Issue by suhwan-cho** [z-x-yang/CFBI#27]
Hi, thanks for your great work!

By the way, I have a question about testing CFBI on the YouTube-VOS dataset.
How is the input stride set? 1 (all frames) or 5 (default)?
And how is the inference speed calculated?

**Comment by z-x-yang** [comment]
"We recorded the inference speed of CFBI by using one NVIDIA Tesla V100 GPU. Besides, we used a multi-object speed instead of a single-object. A large portion of the sequences in VOS datasets contains multiple objects, and CFBI is good at processing multiple objects simultaneously."

During both the training and testing, we follow the default setting of YouTube-VOS. All the video sequences are about 6FPS instead of 24FPS. Notably, YouTube-VOS provided all the 24FPS image frames. Testing with dense frames should significantly improve the performance.

**Comment by suhwan-cho** [comment]
I understand it clearly!
Thank you very much for your help : )
