### ISSUE TITLE
Why doesn't CFBI need Pretraining?

### ISSUE THREAD

**Issue by hzxie** [z-x-yang/CFBI#3]
The Space-Time Memory Networks (Oh et al., ICCV 2019) relies pretraining on the synthetic dataset. I wonder why doesn't CFBI need pretraining?

**Comment by z-x-yang** [comment]
It's not correct that CFBI doesn't need pretraining, because I didn't try to pretrain CFBI on the large synthetic dataset, which 
is elaborate, although may further improve CFBI's performance.

The correct statement is that CFBI outperforms Space-Time Memory Networks (STM) without the synthetic dataset. The key reason for this is that CFBI processes foreground and background simultaneously. The foreground & background mechanism will implicitly impose the prediction of the foreground to be more contrastive, making the training process to be more effective. More explanation can be found in the Introduction of our paper.

**Comment by hzxie** [comment]
@z-x-yang 
Thank you for your response.
BTW, when will the source code available?

**Comment by hzxie** [comment]
In Table 3 of your manuscript, CFBI has a JF mean of  74.9, which is trained with DAVIS 2017 only.

Is the above statement right?

**Comment by z-x-yang** [comment]
In the ablation study, we trained CFBI with DAVIS-2017 only. But when comparing to the state-of-the-art methods on DAVIS, we trained with DAVIS-2017 + YouTube-VOS. Note that STM used DAVIS-2017 + YouTube-VOS + the synthetic dataset. Thus, we indeed outperform STM without the synthetic dataset.

If everything goes well, you will see the source code by the end of this month.

**Comment by hzxie** [comment]
Thank you for your reply.

Actually, The backbone of STM is ResNet pretrained on the ImageNet.
FEELVOS adopts DeepLab as the backbone model that is pretrained on ImageNet and COCO.
CFBI, which can be regarded as an extension of FEELVOS.

Therefore, the DeepLab backbone has more stronger ability in segmenting images than ResNet. That's why FEELVOS and CFBI do not need pretraining.
What's your opinion?

**Comment by z-x-yang** [comment]
Yes, DeepLab backbone is good at segmenting images and will help the training of VOS. But this doesn't mean that pretraining on synthetic datasets is useless when using DeepLab backbone. FEELVOS adopts a very strong DeepLab backbone, Xception-DeepLab-V3. However, the performance of FEELVOS is much weaker than STM. In contrast, our CFBI uses a weaker backbone, ResNet101-DeepLab-V3, and we perform much better. In other words, DeepLab is useful but not the most critical. The most critical part is the VOS architecture, not the backbone, not the synthetic datasets.

In my opinion, I believe that pretraining on synthetic datasets may further improve the performance of FEELVOS or CFBI. However, CFBI proves that it's possible to achieve state-of-the-art performance without synthetic datasets.

**Comment by hzxie** [comment]
I am appreciated for your patient response!

**Comment by z-x-yang** [comment]
It's my pleasure.
