### ISSUE TITLE
Join-Label

### ISSUE THREAD

**Issue by IIAT-MR-LL** [z-x-yang/CFBI#6]
In YouTube-VOS, not all the objects appear in the first frame for the first time. Thus, we have to introduce new labels for new objects, if necessary.
   if not sample['meta']['flip'] and not(current_label is None) and join_label is None:
          join_label = current_label

In evaluation, I cannot understand the function of join label, can you explain it ?

**Comment by z-x-yang** [comment]
Such as Seq "00f88c4f0a" in the validation split of YouTube-VOS, which has two objects, man and skateboard. The man appears in the first frame for the first time, but the skateboard appears in the third frame. Thus we need to use both the first and the third frames to be reference frames.

For DAVIS, all the objects appear in the first frame for the first time. In the meantime, "join label" is not necessary.

Different from most of the VOS methods, CFBI processes all the objects simultaneously, instead of one by one.

**Comment by z-x-yang** [comment]
If you have no more questions, I'll close this issue. Thanks.
